mouse:
  url:
    launcher:
      program: open

window:
  padding:
    x: 8
    y: 0

# Font configuration (changes require restart)
font:
  # The size to use.
  size: 16
  # The normal (roman) font face to use.
  normal:
    family: Cousine NF
    # Style can be specified to pick a specific face.
    style: Regular

  # The bold font face
  bold:
    family: Cousine NF
    # Style can be specified to pick a specific face.
    style: Bold

  # The italic font face
  italic:
    family: Cousine NF
    # Style can be specified to pick a specific face.
    style: Italic

# key binds
key_bindings:
  - { key: Space,  mods: Control, mode: Vi, action: ReceiveChar }
  - { key: Space,  mods: Control,           action: ReceiveChar }

# Colors (Gruvbox dark)
colors:
  # Default colors
  primary:
    # hard contrast: 
    # background: '0x1d2021'
    background: '0x282828'
    # soft contrast: 
    # background: '0x32302f'
    foreground: '0xebdbb2'

  # Normal colors
  normal:
    black:   '0x282828'
    red:     '0xcc241d'
    green:   '0x98971a'
    yellow:  '0xd79921'
    blue:    '0x458588'
    magenta: '0xb16286'
    cyan:    '0x689d6a'
    white:   '0xa89984'

  # Bright colors
  bright:
    black:   '0x928374'
    red:     '0xfb4934'
    green:   '0xb8bb26'
    yellow:  '0xfabd2f'
    blue:    '0x83a598'
    magenta: '0xd3869b'
    cyan:    '0x8ec07c'
    white:   '0xebdbb2'
