#!/bin/bash
#
# Install important packages AND
# Symlink dotfiles in home with dotfiles in this folder.
# Backs up home files in the dotfiles/backup folder.
#
# installs files passed or .* if this script is run with no arguments.

# ignore installing those files, they are not to be symlinked
GLOBIGNORE='.:..:.DS_Store:.git:.gitignore'
HOMEBREW_PACKAGES="autoenv curl fzf git git-extras nvm the_silver_searcher
tmux tree vim"
NPM_GLOBALS="grunt gulp browserify jshint"

is_installed () {
  # This works with scripts and programs. For more info, check
  # http://goo.gl/B9683D
  type $1 &> /dev/null 2>&1
  return "$?"
}

is_brew_installed () {
  brew --prefix "$1" &> /dev/null
  return "$?"
}

install_homebrew () {
  if ! is_installed brew; then
    echo "installing brew."
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  fi

  for package in $HOMEBREW_PACKAGES; do
    if ! is_brew_installed $package; then
      echo "installing $package"
      brew install $package
    fi
  done
}

install_node () {
  if ! is_installed node; then
    echo "installing node with nvm."
    nvm install node

    # reclaim ownership of the ~/.npm module
    sudo chown -R $(whoami) ~/.npm

    echo "installing node packages"
    npm install -g "${NPM_GLOBALS}"
  fi
}

install_oh_my_zsh () {
  if ! [[ -d ~/.oh-my-zsh ]] ; then
    sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

    # make zsh default shell
    chsh -s `which zsh`
  fi
}

create_backup_folder () {
  mkdir -p "./backup"
}

backup_file () {
  local file="$1"
  local current_dir="$2"

  if [[ -f ${file} ]] || [[ -d ${file} ]]; then
    echo "backing up ${file} to ${current_dir}/backup..."
    mv "${file}" "${current_dir}/backup"
    return "$?"
  fi
}

install_file () {
  local file="$1"
  local current_dir="$2"
  local dot_file_path="${current_dir}/${file}"

  # We don't want to install on top of symlinks
  if [[ -L ${file} ]]; then
    echo "${file} is already installed."
  elif [[ -e ${dot_file_path} ]]; then
    backup_file "${file}" "${current_dir}"
    if [[ "$?" -ne 0 ]]; then
      echo "Could not backup ${file}."
      return 1
    fi

    echo "installing ${file}"
    ln -s "${dot_file_path}" "${HOME}/${file}"
  fi
}

main () {
  local dot_files="${@:-.*}"
  local current_dir
  current_dir="$(pwd)"

  if ! [ "$#" -ne 0 ]; then
    echo "=============================="
    echo "Installing missing packages: $HOMEBREW_PACKAGES"
    install_homebrew
    install_node
    install_oh_my_zsh
    echo ""
  fi

  create_backup_folder
  echo "=============================="
  echo "Symlinking dotfile(s): $dot_files"
  for dot_file in ${dot_files}; do
    cd "${HOME}"
    install_file "${dot_file}" "${current_dir}"
    cd "${current_dir}"
  done
}

main "$@"

unset GLOBIGNORE
