#!/bin/bash

today=$(date -d $(date +%F) +%Y-%m-%d)
db="$HOME/ws/counts.sqlite"
now=$(sqlite3 $db "select count(*) from saveCount where day = '$today'")
avg=$(sqlite3 $db "$(cat $HOME/.config/polybar/average.sql)")

echo "$now / $avg"
