#!/bin/bash

session="build"

lower() {
  echo "$1" | tr '[:upper:]' '[:lower:]'
}

has() {
  name="$1"
  symbol_up="$2"
  symbol_down="$3"
  target="$session:$name"
  if tmux has-session -t "$target/iso" &> /dev/null; then
    echo "$symbol_up$symbol_up"
  elif tmux has-session -t "$target" &> /dev/null; then
    echo "$symbol_up"
  else
    echo "$symbol_down"
  fi
}

A=$(has "start/aldoshoes" "A")
I=$(has "start/callitspring" "C")
G=$(has "start/globoshoes" "G")
C=$(has "start/composer" "C")
R=$(has "start/redis" "R")
N=$(has "start/nginx" "N")
S=$(has "start/simplified" " ")

echo -n "$A$I$G$R$N$C$S"
