#!/bin/bash

source /home/charles/.config/colors.sh
# TICK="✓"
# CROSS="✗"

# echo $neutral_orange
OVERDUE="%{F$neutral_red}"
URGENT="%{F$neutral_orange}"
DUETODAY="%{F$bright_yellow}"
DUETOMORROW="%{F$bright_yellow}"
task="task rc.context=none"

has_at_least_1() {
  count=$($task +READY "$@" count 2> /dev/null)
  [[ $count -gt "0" ]]
}

if has_at_least_1 +OVERDUE; then
  echo "$OVERDUE"
elif has_at_least_1 +DUETODAY; then
  echo "$DUETODAY"
elif has_at_least_1 +DUETOMORROW; then
  echo "$DUETOMORROW"
elif has_at_least_1 urgency \> 20; then
  echo "$URGENT"
else
  echo ""
fi
